-- Auto-generated by CodeBuddy at 2025-09-13 10:35:10
INSERT OR REPLACE INTO cw_line (line_id, line_name) VALUES (1, '1号线');
INSERT OR REPLACE INTO cw_line (line_id, line_name) VALUES (2, '2号线');
INSERT OR REPLACE INTO cw_line (line_id, line_name) VALUES (3, '3号线');