-- Auto-generated by CodeBuddy at 2025-09-13 10:35:10
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (1, 4, 1, 1);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (2, 15, 1, 1);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (3, 4, 1, 2);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (4, 15, 1, 2);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (5, 10, 1, 3);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (6, 15, 1, 3);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (7, 10, 1, 4);
INSERT OR REPLACE INTO cw_logic_station (id, station_id, line_id, station_type) VALUES (8, 15, 1, 4);