-- refresh 2025-09-13T10:18:06+08:00
-- 导入列车时刻表明细（cw_train_schedule_detail）
-- 列名与 JSON 完全一致：arrive_time, depart_time；不使用 sequence_order；主键使用 train_schedule_detail_id
-- 先清理 101~108 范围以确保幂等
DELETE FROM cw_train_schedule_detail WHERE train_schedule_id BETWEEN 101 AND 108;

-- schedule 101，上行，从站1到20
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (1, 1, 101, 1, '06:00:00', '06:01:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (2, 1, 101, 2, '06:05:00', '06:06:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (3, 1, 101, 3, '06:10:00', '06:11:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (4, 1, 101, 4, '06:15:00', '06:16:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (5, 1, 101, 5, '06:20:00', '06:21:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (6, 1, 101, 6, '06:25:00', '06:26:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (7, 1, 101, 7, '06:30:00', '06:31:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (8, 1, 101, 8, '06:35:00', '06:36:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (9, 1, 101, 9, '06:40:00', '06:41:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (10, 1, 101, 10, '06:45:00', '06:46:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (11, 1, 101, 11, '06:50:00', '06:51:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (12, 1, 101, 12, '06:55:00', '06:56:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (13, 1, 101, 13, '07:00:00', '07:01:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (14, 1, 101, 14, '07:05:00', '07:06:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (15, 1, 101, 15, '07:10:00', '07:11:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (16, 1, 101, 16, '07:15:00', '07:16:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (17, 1, 101, 17, '07:20:00', '07:21:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (18, 1, 101, 18, '07:25:00', '07:26:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (19, 1, 101, 19, '07:30:00', '07:31:00', 1, 5, 1, 1);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (20, 1, 101, 20, '07:35:00', '07:36:00', 1, 5, 1, 1);
-- schedule 102，下行，从站20到1
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (21, 1, 102, 20, '08:00:00', '08:01:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (22, 1, 102, 19, '08:05:00', '08:06:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (23, 1, 102, 18, '08:10:00', '08:11:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (24, 1, 102, 17, '08:15:00', '08:16:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (25, 1, 102, 16, '08:20:00', '08:21:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (26, 1, 102, 15, '08:25:00', '08:26:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (27, 1, 102, 14, '08:30:00', '08:31:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (28, 1, 102, 13, '08:35:00', '08:36:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (29, 1, 102, 12, '08:40:00', '08:41:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (30, 1, 102, 11, '08:45:00', '08:46:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (31, 1, 102, 10, '08:50:00', '08:51:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (32, 1, 102, 9, '08:55:00', '08:56:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (33, 1, 102, 8, '09:00:00', '09:01:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (34, 1, 102, 7, '09:05:00', '09:06:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (35, 1, 102, 6, '09:10:00', '09:11:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (36, 1, 102, 5, '09:15:00', '09:16:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (37, 1, 102, 4, '09:20:00', '09:21:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (38, 1, 102, 3, '09:25:00', '09:26:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (39, 1, 102, 2, '09:30:00', '09:31:00', 1, 5, 1, 2);
INSERT OR REPLACE INTO cw_train_schedule_detail (train_schedule_detail_id, line_id, train_schedule_id, station_id, arrive_time, depart_time, stop_time, run_time, stop_type, direction) VALUES (40, 1, 102, 1, '09:35:00', '09:36:00', 1, 5, 1, 2);